# Generated by Django 6.0.7 on 2026-07-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_level',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
