# Generated by Django 6.0.7 on 2026-07-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_classlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='class_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'class_level')},
        ),
    ]
