# Generated by Django 6.0.7 on 2026-07-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examattempt_tab_switches_examattempt_violations'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_level',
            field=models.CharField(blank=True, choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SS1', 'SS1'), ('SS2', 'SS2'), ('SS3', 'SS3'), ('Level 100', 'Level 100'), ('Level 200', 'Level 200'), ('Level 300', 'Level 300'), ('Level 400', 'Level 400')], max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='class_level',
            field=models.CharField(blank=True, choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SS1', 'SS1'), ('SS2', 'SS2'), ('SS3', 'SS3'), ('Level 100', 'Level 100'), ('Level 200', 'Level 200'), ('Level 300', 'Level 300'), ('Level 400', 'Level 400')], max_length=50),
        ),
    ]
