# Generated by Django 6.0.7 on 2026-07-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_category_class_level_alter_category_name_and_more'),
        ('exams', '0003_exam_class_level_question_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Controls whether students see this exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='exams', to='courses.category'),
        ),
        migrations.AddField(
            model_name='exam',
            name='visible_from',
            field=models.DateTimeField(blank=True, help_text='Auto-reveal at this time', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='visible_until',
            field=models.DateTimeField(blank=True, help_text='Auto-hide at this time', null=True),
        ),
    ]
